In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

# 读取CSV文件并指定换行符为'<br/>'，然后将'<br/>'替换为换行符'\n'
with open('reviews.csv', 'r', encoding='utf-8') as file:
    csv_content = file.read().replace('<br/>', '\n')


# 将替换后的内容写入新的临时文件，显式指定编码为'utf-8'
with open('temp_reviews.csv', 'w', encoding='utf-8') as file:
    file.write(csv_content)


# 使用 Pandas 读取替换后的临时文件
reviews = pd.read_csv('temp_reviews.csv')

# 删除临时文件
import os
os.remove('temp_reviews.csv')

In [3]:
reviews['comments'] = reviews['comments'].str.replace('\n', '')

In [4]:
reviews.shape

(40522, 6)

In [5]:
reviews = reviews.dropna(subset=['comments'])

In [6]:
from langdetect import detect, LangDetectException

# 假设df是你的评论数据DataFrame
def is_english(text):
    try:
        return detect(text) == 'en'
    except LangDetectException:
        return False

# 应用函数检查每条评论是否为英文
reviews['is_english'] = reviews['comments'].apply(is_english)

# 筛选出所有评论都是英文的listing_id
english_reviews = reviews[reviews['is_english']]

In [7]:
english_reviews

,listing_id,id,date,reviewer_id,reviewer_name,comments,is_english
0,71609,7.938800e+05,2011-12-19,1456140.0,Max,The rooms were clean and tidy. Beds very comfo...,True
1,71609,1.731810e+06,2012-07-17,1804182.0,Zac,Good space and quite an interesting home in a ...,True
2,71609,2.162194e+06,2012-09-01,3113461.0,Zahra,It was a comfortable place. Belinda was a kind...,True
3,71609,2.190615e+06,2012-09-04,1432123.0,Helmut,We are four mature age travellers and stayed f...,True
4,71609,3.221837e+06,2013-01-02,2759938.0,Jack,Belinda is a great host! She helps you wheneve...,True
...,...,...,...,...,...,...,...
40517,1029731383146744109,1.037353e+18,2023-12-02,518880983.0,Nick,"The pictures are stock photos, He didn't reply...",True
40518,1008723963440015334,1.030150e+18,2023-11-22,529655152.0,Arun,Responsive staff and a great location to stay at,True
40519,1009310616747753745,1.041670e+18,2023-12-08,439796332.0,Jonathan,We had a great stay at the hotel! It’s nice an...,True
40520,1009310616747753745,1.048957e+18,2023-12-18,460292893.0,Yann Teng,Need to provide more mirror,True
40521,1009662020699585686,1.017740e+18,2023-11-05,464949236.0,John,"Very friendly and helpful staff, clean rooms, ...",True

In [8]:
listings = pd.read_csv('listings.csv')
listings.head(8)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,71609,https://www.airbnb.com/rooms/71609,20231226204029,2023-12-27,previous scrape,Villa in Singapore · ★4.44 · 2 bedrooms · 3 be...,NaN,NaN,https://a0.muscache.com/pictures/24453191/3580...,367042,...,4.78,4.26,4.32,NaN,f,5,0,5,0,0.13
1,71896,https://www.airbnb.com/rooms/71896,20231226204029,2023-12-26,city scrape,Home in Singapore · ★4.16 · 1 bedroom · 1 bed ...,NaN,NaN,https://a0.muscache.com/pictures/2440674/ac4f4...,367042,...,4.43,4.17,4.04,NaN,f,5,0,5,0,0.16
2,71903,https://www.airbnb.com/rooms/71903,20231226204029,2023-12-26,city scrape,Home in Singapore · ★4.41 · 1 bedroom · 2 beds...,NaN,Quiet and view of the playground with exercise...,https://a0.muscache.com/pictures/568743/7bc623...,367042,...,4.64,4.50,4.36,NaN,f,5,0,5,0,0.30
3,275343,https://www.airbnb.com/rooms/275343,20231226204029,2023-12-26,city scrape,Rental unit in Singapore · ★4.40 · 1 bedroom ·...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1439258,...,4.42,4.53,4.63,S0399,t,51,0,51,0,0.15
4,275344,https://www.airbnb.com/rooms/275344,20231226204029,2023-12-26,city scrape,Rental unit in Singapore · ★4.27 · 1 bedroom ·...,NaN,Bus stop <br />Food center <br />Supermarket,https://a0.muscache.com/pictures/miso/Hosting-...,1439258,...,4.50,4.63,4.13,S0399,t,51,0,51,0,0.11
5,289234,https://www.airbnb.com/rooms/289234,20231226204029,2023-12-27,previous scrape,Home in Singapore · ★4.83 · 3 bedrooms · 5 bed...,NaN,A quiet and clean environment,https://a0.muscache.com/pictures/24395933/8e2f...,367042,...,4.67,4.33,4.45,NaN,t,5,0,5,0,0.09
6,294281,https://www.airbnb.com/rooms/294281,20231226204029,2023-12-27,city scrape,Rental unit in Singapore · ★4.43 · 2 bedrooms ...,NaN,NaN,https://a0.muscache.com/pictures/4607862/87f42...,1521514,...,4.66,4.52,4.39,NaN,f,7,1,6,0,0.90
7,324945,https://www.airbnb.com/rooms/324945,20231226204029,2023-12-26,city scrape,Rental unit in Singapore · ★3.50 · 1 bedroom ·...,NaN,NaN,https://a0.muscache.com/pictures/f8c7598c-a0b1...,1439258,...,4.06,3.82,3.76,S0399,f,51,0,51,0,0.12